# Generated by Django 5.2.3 on 2026-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_admin_notes_order_courier_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tracking_url',
            new_name='courier_tracking_url',
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
