# Generated by Django 6.0.3 on 2026-03-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
